'use client'

import { useEffect, useState } from 'react'
import { MapPin, Save, UserRound } from 'lucide-react'
import toast from 'react-hot-toast'

export default function ClientProfileSettings() {
  const [city, setCity] = useState(''); const [state, setState] = useState(''); const [age, setAge] = useState(''); const [bio, setBio] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  useEffect(() => { fetch('/api/users/me/profile', { credentials: 'include' }).then(r => r.ok ? r.json() : null).then(data => { if (data) { setCity(data.city || ''); setState(data.state || ''); setAge(data.age ? String(data.age) : ''); setBio(data.bio || '') } }).finally(() => setLoading(false)) }, [])
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { setSaving(true); const response = await fetch('/api/users/me/profile', { method: 'PATCH', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ city, state, age, bio }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); toast.success('Perfil de usuário atualizado.') } catch (error) { toast.error(error instanceof Error ? error.message : 'Não foi possível salvar o perfil.') } finally { setSaving(false) } }
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800/70"><div className="flex gap-3"><UserRound className="mt-1 h-5 w-5 text-primary-600" /><div><h2 className="font-semibold text-slate-900 dark:text-white">Perfil de usuário</h2><p className="text-sm text-slate-600 dark:text-slate-400">Essas informações poderão ser vistas por anunciantes no chat e nos Stories.</p></div></div><form onSubmit={submit} className="mt-4 space-y-3"><div className="grid gap-3 sm:grid-cols-[1fr,90px,100px]"><input className="rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-slate-900 dark:border-slate-600 dark:bg-slate-900 dark:text-white" value={city} onChange={e => setCity(e.target.value)} placeholder="Cidade (opcional)" maxLength={100} /><input className="rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-slate-900 uppercase dark:border-slate-600 dark:bg-slate-900 dark:text-white" value={state} onChange={e => setState(e.target.value.toUpperCase())} placeholder="UF" maxLength={2} /><input className="rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-slate-900 dark:border-slate-600 dark:bg-slate-900 dark:text-white" value={age} onChange={e => setAge(e.target.value.replace(/\D/g, ''))} placeholder="Idade" inputMode="numeric" min={18} max={100} /></div><textarea className="min-h-24 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-slate-900 placeholder-slate-500 dark:border-slate-600 dark:bg-slate-900 dark:text-white" value={bio} onChange={e => setBio(e.target.value)} placeholder="Uma pequena bio (opcional)" maxLength={300} /><div className="flex items-center justify-between gap-3"><span className="inline-flex items-center gap-1 text-xs text-slate-500"><MapPin className="h-3.5 w-3.5" />Não informe endereço exato.</span><button disabled={loading || saving} className="inline-flex items-center gap-2 rounded-xl bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Save className="h-4 w-4" />{saving ? 'Salvando...' : 'Salvar perfil'}</button></div></form></section>
}
